baseURL = "http://figjam.food.s3-website-eu-west-1.amazonaws.com"
languageCode = "en-uk"
title = "The FIGJAM recipe book"
theme = "recipes"

[params]
  author = "FIGJAM qualified professionals"
  description = "The FIGJAM recipe book"

[deployment]


[[deployment.targets]]
# An arbitrary name for this target.
name = "figjam.food"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://figjam.food?region=eu-west-1"